{% set name = "grib2io-interp" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 922cf48f940d13cc083408ed429a8d735431c133b379660e7d4450ca30e5ae63

build:
  skip: true  # [win]
  number: 0
  script_env:
    - SP_DIR={{ PREFIX }}
    - IP_DIR={{ PREFIX }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nceplibs-ip                         # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - setuptools >=61.0                   # [build_platform != target_platform]
  host:
    - nceplibs-ip
    - numpy
    - pip
    - python
    - setuptools >=61.0
  run:
    - nceplibs-ip
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip
    - nceplibs-ip

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
