{% set name = "grib2io-interp" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grib2io-interp-{{ version }}.tar.gz
  sha256: 96c67101bdb721e641b107d3387620aa567fa1f6299560fb9e6704df56b52c58

build:
  skip: true  # [win or py<38]
  number: 0
  script_env:
    - SP_DIR={{ PREFIX }}
    - IP_DIR={{ PREFIX }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=61.0,<62.1.0
    - numpy
    - pip
    - nceplibs-ip
    - nceplibs-sp
  run:
    - python
    - numpy
    - nceplibs-ip
    - nceplibs-sp

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - timcera
    - EricEngle-NOAA
