{% set name = "grib2io-interp" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grib2io-interp-{{ version }}.tar.gz
  sha256: 8dcf8a565b600e6963d651a852cd667e715a1740cdc4a55ad9bfc6209744b68f

build:
  skip: true  # [win]
  number: 4
  script_env:
    - SP_DIR={{ PREFIX }}
    - IP_DIR={{ PREFIX }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools >=61.0
    - nceplibs-ip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - nceplibs-ip

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip
    - nceplibs-ip

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
