{% set name = "grib2io-interp" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grib2io-interp-{{ version }}.tar.gz
  sha256: 70e19d71a5208a2ea8692f3cc1c4cadeeaec4375a1dd91af15dc88e2c23faf3e

build:
  number: 1
  script_env:
    - SP_DIR={{ PREFIX }}              # [not win]
    - IP_DIR={{ PREFIX }}              # [not win]
    - SP_DIR={{ PREFIX }}/Library/bin  # [win]
    - IP_DIR={{ PREFIX }}/Library/bin  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('fortran') }}           # [not win]
    - m2w64-gcc                           # [win]
    - m2w64-gcc-fortran                   # [win]
    - ninja                               # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nceplibs-ip                         # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - setuptools >=61.0                   # [build_platform != target_platform]
  host:
    - nceplibs-ip
    - numpy
    - pip
    - python
    - setuptools >=61.0
  run:
    - m2w64-gcc-fortran  # [win]
    - m2w64-gcc-libs     # [win]
    - nceplibs-ip
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip
    - nceplibs-ip

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
