{% set name = "grib2io-interp" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grib2io-interp-{{ version }}.tar.gz
  sha256: 8dcf8a565b600e6963d651a852cd667e715a1740cdc4a55ad9bfc6209744b68f
  patches:
    - 0001-FEAT-Have-find_library-search-through-LD_LIBRARY_PAT.patch

build:
  skip: true  # [win]
  number: 4
  script_env:
    - SP_DIR={{ PREFIX }}        # [not win]
    - IP_DIR={{ PREFIX }}        # [not win]
    - SP_DIR={{ PREFIX }}/Library/bin        # [win]
    - IP_DIR={{ PREFIX }}/Library/bin        # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nceplibs-ip                         # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - setuptools >=61.0                   # [build_platform != target_platform]
  host:
    - nceplibs-ip
    - numpy
    - pip
    - python
    - setuptools >=61.0
  run:
    - nceplibs-ip
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - grib2io_interp
  commands:
    - pip check
  requires:
    - pip
    - nceplibs-ip

about:
  summary: Interpolation component for grib2io providing a Python interface to NCEPLIBS-ip
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/grib2io-interp/

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
